### ISSUE TITLE
__builtin_unreachable() not properly handled by Apple LLVM version 6.1.0?

### ISSUE THREAD

**Issue by aferrero2707** [darktable-org/rawspeed#104]
Using Apple LLVM version 6.1.0, the compilation of 

```    rawspeed/src/fuzzers/HuffmanTable/main.cpp```

stops with an error like

    ..../rawspeed/src/fuzzers/HuffmanTable/main.cpp:84:3: error: code will never be
      executed [-Werror,-Wunreachable-code]
      __builtin_unreachable();

while I guess it should simply proceed with the compilation... can this line be safely commented for not-so-recent versions of clang? Or is there another solution that does not involve upgrading the compiler?

Thanks!

**Comment by LebedevRI** [comment]
How are you building?
As part of some other build?
If yes, then i'd recommend https://github.com/darktable-org/darktable/blob/f92f3a2577bda0d2faf73f496b9d687e518dac88/src/external/CMakeLists.txt#L16-L17

**Comment by LebedevRI** [comment]
Regardless, i'll add a specialcasing into cmakelists.txt to disable `-Wunreachable-code` if it to complain on that code.
Thank you for the report.

**Comment by aferrero2707** [comment]
Thanks, much appreciated!

By the way, since I am using RawSpeed as a bundled library for the RAW decoding in my [image editor](https://github.com/aferrero2707/PhotoFlow/tree/stable), do I need all this fuzzers code or can it be safely disabled?

**Comment by LebedevRI** [comment]
@aferrero2707 no, you can safely disable all that
Basically just copy [darktable/src/external/CMakeLists.txt](https://github.com/darktable-org/darktable/blob/master/src/external/CMakeLists.txt), and it should be fine.
It'll be kept updated to only build the library but nothing else.

**Comment by LebedevRI** [comment]
@aferrero2707 please do check and confirm that this actually fixed the issue you were hitting.
