### ISSUE TITLE
Panasonic G9 high-resolution RW2

### ISSUE THREAD

**Issue by shoffmeister** [darktable-org/rawspeed#126]
darktable 2.4.3 (for Windows) appears to fail reading Panasonic LUMIX DC-G9 high-resolution RW2 raw files.

The error message emitted by darktable is "failed to read camera white balance".

The photos have the following dimensions (according to exiftool):
* high-resolution item ("HR"): 10368x7776
* "simul record normal shot" (simulate recording a single normal shot = "SIM"): 5184x3888

If one was to trust the documentation, then SIM "should be" a totally plain normal RW2 file: "Saves the first picture of pictures taken before the combining process ... [is started]"

Whatever hides inside HR - I have no idea. Theoretically this is the combined result of a total of eight pixel-shifted exposures.

**Comment by shoffmeister** [comment]
FWIW, RawTherapee 5.4 willingly opens both RW2, but reads /renders total garbage for both files.

**Comment by LebedevRI** [comment]
Is there a sample on RPU?

**Comment by shoffmeister** [comment]
I just (thought that I) uploaded two files (32 MB, 125 MB) onto RPU - I got "thanks", but I do not see these files in the repo list?

**Comment by shoffmeister** [comment]
FWIW, the Panasonic documentation for the Panasonic LUMIX DC-G9 can be found at https://eww.pavc.panasonic.co.jp/dscoi/DC-G9/EG_EC_EF_EB/DC-G9_DVQP1406ZA_eng.pdf - the magic keyword is "[High Resolution Mode]" (page 196)

**Comment by shoffmeister** [comment]
FWIW, SILKYPIX Developer Studio 4.4 SE (Version: 4.4.14.5) - for Panasonic cameras only, runs on Windows and OSX - is able to open these raw files and render them.

Don't slaughter me for mentioning that https://www.isl.co.jp/SILKYPIX/english/p/support/download/ has a download available and that installation on Windows is painless, not needing anything like a serial number or what-not. But that download is limited to processing files produced by Panasonic cameras.

**Comment by LebedevRI** [comment]
> I got "thanks", but I do not see these files in the repo list?

There is a pre-review.
Thanks for submitting those samples, but they are really unhelpful.
Please contribute something better/more recognizable, like daylight landscape.

I have taken a quick look at the raws themselves, they look to be still compressed,
but interestingly the width is no longer a multiple of `14`, which breaks all later assumptions.

**Comment by shoffmeister** [comment]
I will go hunting for daylight ASAP ;)

May I suggest that https://raw.pixls.us/ gets some language which indicates preferences general preferences? Right now the web site makes it appear as if anything is good enough. Perhaps mention: "Ideally a correctly exposed photo, taken in daylight, of a landscape"?

**Comment by LebedevRI** [comment]
You mean like this one:
![image](https://user-images.githubusercontent.com/88600/40143649-ad837a34-5964-11e8-8977-c32664302939.png)

**Comment by shoffmeister** [comment]
I mean the (missing) bullet item / paragraph immediately before "We are **NOT** looking for:" ;)

**Comment by shoffmeister** [comment]
FWIW, Adobe DNG Converter 10.1 is able to read both files and transform them into DNGs of size 13 MB and 48 MB, respectively.

Note how the files shrank quite considerably from RW2 -> DNG (32 -> 13 MB; 125 -> 48 MB), while declared resolution remains at 5184x3888 and 10368x7776 respectively.

**Comment by shoffmeister** [comment]
Ah ... and now this gets rather fancy: darktable reads the DNG files produced by Adobe DNG Converter 10.1 - and, according to darktable (image information width/height), the resolution of these DNG files is 5280x3904 and 10480x7794.

I have reconfirmed that exiftool shows 5184x3888 and 10368x7776 for both RW2 and DNG.

**Comment by shoffmeister** [comment]
I have just uploaded two new files at https://raw.pixls.us/

These new files show the nice green tree watered by rainy weather just in front of my door. Better subjects are conditional to better weather ;)

**Comment by shoffmeister** [comment]
I just discovered that FastRawViewer 1.4.6 (https://www.fastrawviewer.com/blog/FastRawViewer-1-4-6-release) has added support for the Panasonic G9 in high-res mode.

Perhaps @LibRaw might be able to chime in?

**Comment by LibRaw** [comment]
[s]We'll publish G9 support in next snapshot (end of summer, or a little later). Now we're focused on 0.19 final polishing[/s]

Correction: it is supported in LibRaw 0.19

**Comment by shoffmeister** [comment]
Ah: "Alexey Danilchenko's GH5S/G9-hires patch

disable rawspeed for new panasonic decoder"

https://github.com/LibRaw/LibRaw/commit/9fc4e05565ccda07e8479b197cf8f166f94f53c6

**Comment by LibRaw** [comment]
I was sure, we've added it to 0.19, but looked into code and have not see it,

The problem was: I've looked into 0.19-tarball dcraw/dcraw.c which is original Dave Coffin's code.

Yes, G9/GH5s are already supported by current 0.19 pre-release (beta5)

**Comment by LibRaw** [comment]
(G9-> read as G9 high res)

**Comment by shoffmeister** [comment]
Reading around, it would seem as if Panasonic is switching to a new raw format for the newer cameras. Specifically, the Panasonic DC-GH5S seems to use the same format "natively" as the Panasonic DC-G9 in its dedicated high-resolution mode. (GH5s raws can be found at https://www.dpreview.com/reviews/panasonic-lumix-dc-gh5s-review/6, nothing on RPU as I am writing this)

The commit in the libraw repo takes care of this, by way of (also) supporting the 14 bit resolution of the GH5s for format version 5.

Also in the libraw repo is peculiar handling of black-level information for the new format version 5, see https://github.com/LibRaw/LibRaw/commit/f86a450c8af1d0af4435cc3f1e00b40d2a0167fc (pana_encoding == 4 is old, pana_encoding == 5 is the newly introduced raw format)

There is also interesting information in https://github.com/LibRaw/LibRaw/commit/20efe0cce91acd17c76d92e8113d719fed0d3e49 where compression information is read (but, later, this is not used, it would seem).

**Comment by LebedevRI** [comment]
> Reading around, it would seem as if Panasonic is switching to a new raw format for the newer cameras. 

And still not LJPEG
(╯°□°）╯︵ ┻━┻)

**Comment by shoffmeister** [comment]
... which, clueless as I am, I would consider beneficial for my own personal sanity, as LJPEG seems to be using Huffman encoding to (losslessly) compress? (https://en.wikipedia.org/wiki/Lossless_JPEG)

**Comment by LebedevRI** [comment]
Yeah, all these manufacturer-specific compressions (RW2, ARW, ...) are pretty bad even at compressing,
and some even introduce artifacts.

**Comment by shoffmeister** [comment]
Just for the public record: A very exploratory implementation is currently located at https://github.com/shoffmeister/rawspeed/tree/wip/rw2-g9-gh5s-support

**Comment by LebedevRI** [comment]
@shoffmeister hi. i'm not sure if you are still around, and have DC-GH5S camera.
Flashback: the camera supposedly writes 14bit and 12bit raws, but the sample set that exists on RPU,
even the supposedly-12bit raws, internally they are all 14bit raws.

I wonder if that has been fixed in newer firmwares, and maybe now the camera writes different raws?
You can't really tell that from EXIF, but you can add `writeLog(DEBUG_PRIO_EXTRA, "PanasonicDecompressorV5: bpp: %ul", bpp);`
here:
https://github.com/darktable-org/rawspeed/blob/446aa6b30fe97aad0e170e756e5b7fe0145752a9/src/librawspeed/decompressors/PanasonicDecompressorV5.cpp#L67

If that does print both `12` and `14` nowadays, it would be great to get a replacement full sample set for RPU (8 raws, {12bit,14bit} x {4:3, 3:2, 16:9, 1:1}).

**Comment by shoffmeister** [comment]
Sorry, I don't have access to a GH5S, only own a G9.

**Comment by LebedevRI** [comment]
Oh right, i think the GH5S samples originated from somewhere else, sorry.
