### ISSUE TITLE
[2/3] Regression: huffmantable is bad for last decode

### ISSUE THREAD

**Issue by LebedevRI** [darktable-org/rawspeed#128]
Some raws appear not to have padding at the end, so when we do `bs.fill(32);`, we fail.
Changing https://github.com/darktable-org/rawspeed/blob/d41fd6dadc161d1c0bb56463dc35263779fa02f1/src/librawspeed/decompressors/HuffmanTable.h#L309
```diff
-bs.fill(32);
+bs.fill(maxCodePlusDiffLength());
```
seems to help somewhat, but i don't know the full solution yet.

**Comment by LebedevRI** [comment]
@exaexa hi. (+ others affected, who tried this)
With this fix, did you ever seen any NEF's still failing to decode?
Or does this appear to fully resolve the situation?

**Comment by exaexa** [comment]
> With this fix

Which one, the workaround or the "unfucking" commit from May?

I'm pretty sure there weren't any extra issues with the workaround and I think that I'm already on a newer version without the workaround and with the commit. Going to verify ASAP.

**Comment by exaexa** [comment]
Negative, the problem is still present (tested on darktable+rawspeed from git; rawspeed commit 2bc2bf5  is there)

You can get an affected file for testing here: http://e-x-a.org/stuff/_DSC0193.NEF  (not sure if the previous sample I posted to pixls got fixed or not, but it seems more like not).

**Comment by LebedevRI** [comment]
> > With this fix
> 
> Which one, the workaround or the "unfucking" commit from May?

The this one in this issue:

> Changing
> 
> [rawspeed/src/librawspeed/decompressors/HuffmanTable.h](https://github.com/darktable-org/rawspeed/blob/d41fd6dadc161d1c0bb56463dc35263779fa02f1/src/librawspeed/decompressors/HuffmanTable.h#L309)
> 
> Line 309 in [d41fd6d](/darktable-org/rawspeed/commit/d41fd6dadc161d1c0bb56463dc35263779fa02f1)
> 
>  bs.fill(32); 
> ```diff
> -bs.fill(32);
> +bs.fill(maxCodePlusDiffLength());
> ```
> 
> seems to help somewhat, but i don't know the full solution yet.

**Comment by LebedevRI** [comment]
@exaexa please do tell if any of the raws are still broken after this.

**Comment by exaexa** [comment]
There are no more problems with e9a586f in rawspeed. Thanks!

**Comment by LebedevRI** [comment]
HURRAY!
Thanks for checking!
