### ISSUE TITLE
Hasselblad LJPEG issues

### ISSUE THREAD

**Issue by LebedevRI** [darktable-org/rawspeed#144]
Many Hasselblad cameras produce `3FR` with kinda weird, missized `LJPEG`'s - after `M_SOS` marker (i.e. the image)
https://github.com/darktable-org/rawspeed/blob/60655d481d44733c60d2b781c928d91d12de63f9/src/librawspeed/decompressors/AbstractLJpegDecompressor.cpp#L101-L102
we don't 'naturally' finish with `M_EOI`, but the last marker is sudo-truncated.
So even though we properly decoded the image, we still bailout with error.

It happens for (as per the samples on raw.pixls.us)
* H4D
* H4D-40
* H6D-100cMS
* ???

**Comment by LebedevRI** [comment]
Same for _some_ leica dng's (no sample on RPU, samples @ https://redmine.darktable.org/issues/12603).
Perhaps it might be wise to indeed just bailout right after `M_SOS`, without looking for `M_EOI`.
Ugly :/

**Comment by ValZapod** [comment]
It is jot that simple. You need to emulate EOI then. See https://github.com/darktable-org/darktable/issues/11695#issuecomment-1120988605

**Comment by LebedevRI** [comment]
https://github.com/darktable-org/rawspeed/pull/649
