### ISSUE TITLE
Orientation of a .NEF file

### ISSUE THREAD

**Issue by photopea** [darktable-org/rawspeed#155]
Hi guys, I am making my own .NEF parser and I can not get the information about the Orientation of the image (landscape / portrait). The TIFF Orientation tag 274 is always "1" (no transformation needed). I am parsing the Maker Note, but don't see it in there either.

Could you tell me, how do you detect the orientation of .NEF files? I could not find it in your code. Or do you process the pixel data and detect it with AI?

**Comment by LebedevRI** [comment]
> Could you tell me, how do you detect the orientation of .NEF files?

I'm sorry, no idea.

>  I could not find it in your code.

Indeed, that info is out of the scope of this library, it does not read it.

I can refer you to https://github.com/exiv2/exiv2 and https://sno.phy.queensu.ca/~phil/exiftool/

**Comment by photopea** [comment]
I tried to load this .NEF file into Darktable: https://s3.amazonaws.com/Sample_NEFs/pikes-peak.nef.zip . The file was displayed in a Landscape mode, but the preview at the bottom was in a Portrait mode: https://i.imgur.com/PoLcB5Z.jpg

Could you leave my question open for some time, please? Maybe somebody knows it and would not mind giving me an advice.

**Comment by LebedevRI** [comment]
> I tried to load this .NEF file into Darktable: https://s3.amazonaws.com/Sample_NEFs/pikes-peak.nef.zip . The file was displayed in a Landscape mode, but the preview at the bottom was in a Portrait mode: https://i.imgur.com/PoLcB5Z.jpg

That is a darktable bug, not rawspeed's. As i said, this library does not handle orientation.
I'm seeing the same here.
exif dumps:
```
/tmp/pikes-peak.nef$ EXIV2 pikes-peak.nef | grep -i orient
Error: Directory (Last IFD item) with 771 entries considered invalid; not read.
0x0112 Exif.Image.Orientation                       Short       1   2  1  top, left
0x0112 Exif.SubImage1.Orientation                   Short       1   2  1  top, left
0x0112 Exif.SubImage2.Orientation                   Short       1   2  1  top, left
/tmp/pikes-peak.nef$ EXIFTOOL pikes-peak.nef | grep -i orient
[EXIF]          0x0112 Orientation                     : Horizontal (normal)
[EXIF]          0x0112 Orientation                     : Horizontal (normal)
[EXIF]          0x0112 Orientation                     : Horizontal (normal)
```
say that all the "orientation"s specified in that file say it should not be rotated, and is horizontal.
So i think it will be best to ask in a more appropriate https://github.com/exiv2/exiv2

**Comment by photopea** [comment]
Ok, thank you!
