### ISSUE TITLE
Panasonic ZS200 files don't open in darktable

### ISSUE THREAD

**Issue by junkyardsparkle** [darktable-org/rawspeed#178]
Using current git master, Panasonic ZS200 files fail to open. I'm not sure I understand exactly how the `cameras.xml` file is supposed to work, but it *looks* like the ZS200 and TZ202 are conflated within a single definition, with only TZ200 listed as an alias. Maybe one of the other two should also be an alias, rather than mixed together?

EDIT: I had a chance to test this, and the fix in #179 works for me.

**Comment by LebedevRI** [comment]
Please start with contributing full sample set to RPU :)

**Comment by junkyardsparkle** [comment]
I don't own this camera. I just need to load files submitted for LensFun calibration. Anyway, there's nothing wrong with the camera support after fixing the definition. :)

**Comment by LebedevRI** [comment]
I agree that the fix looks correct (i didn't google that those cameras are aliases),
but it is a general policy of not adding things without test coverage.
And since there is no sample for ZS200, there is no test coverage.

**Comment by junkyardsparkle** [comment]
All of those models were *already in the definition*, though; I didn't add any models, just fixed the broken formatting. This is known to be a standard (stupid) thing Panasonic does with regional model names... see the TZ100 definition, for example. Anyway, I have it working for what I needed, so you can close this and wait for somebody to submit samples if you want. In any case, it's worth noting that the current definition doesn't make sense as it is.

**Comment by LebedevRI** [comment]
Hmm, looks like i messed up in https://github.com/darktable-org/rawspeed/commit/1a1e8317f3acfceff736297e6bc637804274e4a6 / https://redmine.darktable.org/issues/12295
Which kind-of stresses the point about tests :/

**Comment by junkyardsparkle** [comment]
I've had plenty of reasonable assumptions backfire on me lately, so I'm not going to argue against that policy. ;)
