### ISSUE TITLE
Lumix DC-G9 RAW file contribution

### ISSUE THREAD

**Issue by Graycard** [darktable-org/rawspeed#182]
Just uploaded four RW2 files of the same target to https://raw.pixls.us/, in 4:3, 3:2, 1:1, and 16:9 aspect ratios.  Hope this helps.  None are modified in any way.  Hope this helps.

**Comment by LebedevRI** [comment]
Thank you.
Don't think any action is needed here, that camera is supported for some time now.
(And, there were [more] samples already.)
