### ISSUE TITLE
getCamera() with prefix-search issue

### ISSUE THREAD

**Issue by LebedevRI** [darktable-org/rawspeed#19]
https://github.com/klauspost/rawspeed/issues/166

I added that api in https://github.com/klauspost/rawspeed/commit/a45724ec3c201b67f5ff732317921c0feca878c6 and https://github.com/klauspost/rawspeed/commit/e1b5ccae3515773755621cee305170fa5ea63808.
And now i have just discovered how it backfires.
With raw file from https://redmine.darktable.org/issues/11354 from `Canon EOS Rebel T6`, which currently has broken alias, it matches to `Canon EOS Rebel T6i`.
That happens because internally "make model mode" is a string, https://github.com/klauspost/rawspeed/blob/a45724ec3c201b67f5ff732317921c0feca878c6/RawSpeed/CameraMetaData.h#L37

**Comment by tredlie** [comment]
This issue still seems to be around. What are the chances of getting this fixed as it brings darktable usage for a Leica M9 to a grinding halt, reporting this camera to be a Mamiya.
Or, maybe, this does not do any harm other than reporting the wrong Maker in the Image Information window in DT. The exported JPG looks OK.

**Comment by LebedevRI** [comment]
I believe i have just fixed it locally. At least the unittest i just wrote no longer fails.
