### ISSUE TITLE
Sony DSC-RX100M7 support

### ISSUE THREAD

**Issue by variadico** [darktable-org/rawspeed#206]
I'm trying to add support in Darktable for RX100M7 RAWs. I'm building Darktable and rawspeed from scratch. I'm using this commit for rawspeed.

```
Subproject commit cf6ee7d7b40a7b7c5ad4b1f38f7ef0b9957def9f
```

I'm getting this error though.

```
bool rawspeed::RawDecoder::checkCameraSupported(const rawspeed::CameraMetaData *, const std::string &, const std::string &, const std::string &), line 171: Camera 'SONY' 'DSC-RX100M7', mode '' not supported, and not allowed to guess. Sorry.
```

Guessing that's because there is no entry for this camera in `cameras.xml`.

There is an Rx100M7 sample already uploaded to raw.pixls.us:

https://raw.pixls.us/getfile.php/3463/nice/Sony%20-%20DSC-RX100M7%20-%2012bit%20compressed%20(3:2).ARW

**Comment by LebedevRI** [comment]
Not updating darkable's rawspeed submodule for the moment:
1. Please open a bug :)
2. They're in rc process, and i have recently landed some widespread changes,
    so not sure yet when i'll be ok doing that.
3. But colot matrix is added, so if you update submodue locally, it will just work.
