### ISSUE TITLE
Don't set frame or stack-size via compiler commandline

### ISSUE THREAD

**Issue by cryptomilk** [darktable-org/rawspeed#211]
Hi Roman,

I've talked to musl developers on IRC in #musl @ freenode about setting stack and frame size.

https://github.com/darktable-org/rawspeed/blob/develop/cmake/compiler-warnings.cmake#L16

This should be done using `pthread_attr_setstacksize()` if really needed for musl libc.

**Comment by LebedevRI** [comment]
`-W<>` are *warning* flags, they do not actually set the limits.

**Comment by LebedevRI** [comment]
To allow forward progress here, can you specify not *what* (current subj), but *why*?

**Comment by cryptomilk** [comment]
You probably get warnings with this if you enable AddressSanitzer. It does some nasty things.

**Comment by LebedevRI** [comment]
Please feel free to post coherent bugreport, if one exists and it's not a duplicate of #212.
