### ISSUE TITLE
LJpegDecompressor check for `cpp` is too strict

### ISSUE THREAD

**Issue by alexvanderberkel** [darktable-org/rawspeed#214]
I converted a CR3 into a DNG file with Adobe DNG converter. Currently darktable is not able to open the DNG file. Terminal shows following error message: 

[rawspeed] (file.dng) void rawspeed::AbstractDngDecompressor::decompress() const, line 208: Too many errors encountered. Giving up. First Error:
rawspeed::LJpegDecompressor::LJpegDecompressor(const rawspeed::ByteStream&, const rawspeed::RawImage&), line 42: Unexpected component count (2)
allocation failed???

In addition the following two error are shown consecutively

(darktable:7246): GLib-GObject-WARNING **: 10:45:48.696: invalid cast from 'GtkBox' to 'GtkGrid'

(darktable:7246): Gtk-CRITICAL **: 10:45:48.696: gtk_grid_attach_next_to: assertion 'GTK_IS_GRID (grid)' failed

**Comment by LebedevRI** [comment]
Please attach the DNG in question.

**Comment by alexvanderberkel** [comment]
DNG files are not allowed as an attachmend and are too big. Link is valid temporarily https://send.firefox.com/download/e60737a68263e269/#c2O81MxWHaJ0R5aZ381qPw

**Comment by LebedevRI** [comment]
> DNG files are not allowed as an attachmend and are to big.

Yep. Putting it in a .zip and attaching works.

**Comment by alexvanderberkel** [comment]
> > DNG files are not allowed as an attachmend and are to big.
> 
> Yep. Putting it in a .zip and attaching works.

Zip was unfortunately still over the 10MB limit...

**Comment by LebedevRI** [comment]
Hmm, that's a new restriction then, i don't recall seeing it before.
That being said i failed to download, link expired.

**Comment by alexvanderberkel** [comment]
Will send you the link via email to avoid that the link will expire to some reasons

**Comment by LebedevRI** [comment]
Is that DualISO?
While it is easy to convince rawspeed to load it
```diff
diff --git a/src/librawspeed/decompressors/LJpegDecompressor.cpp b/src/librawspeed/decompressors/LJpegDecompressor.cpp
index f5d6d86c..64b2fb2b 100644
--- a/src/librawspeed/decompressors/LJpegDecompressor.cpp
+++ b/src/librawspeed/decompressors/LJpegDecompressor.cpp
@@ -39,6 +39,7 @@ LJpegDecompressor::LJpegDecompressor(const ByteStream& bs, const RawImage& img)
     ThrowRDE("Unexpected data type (%u)", mRaw->getDataType());
 
   if (!((mRaw->getCpp() == 1 && mRaw->getBpp() == 2) ||
+        (mRaw->getCpp() == 2 && mRaw->getBpp() == 4) ||
         (mRaw->getCpp() == 3 && mRaw->getBpp() == 6)))
     ThrowRDE("Unexpected component count (%u)", mRaw->getCpp());
```
it is then discarded in darktable.

**Comment by alexvanderberkel** [comment]
It is Dual Pixel Raw

**Comment by LebedevRI** [comment]
Guessed as much.
I'll relax rawspeed-side check, but i'm no going to do about darktable-side thing here.
Feel free to open issue there.

**Comment by jenshannoschwalm** [comment]
@LebedevRI @alexvanderberkel  I got darktable decoding dual pixel dng files.

There is one more thing in rawspeed that "requires relaxing". `bool DngDecoder::decodeBlackLevels(const TiffIFD* raw) {` in DngDecoder.cpp should accept cpp==2 too.

So i suggest it to be
``` 
 if ((mRaw->getCpp() < 1) || (mRaw->getCpp() > 2))
    return false;

```
Can you agree here? And could you modify this or do you want me to do a pr?
BTW it would be nice to push current rawspeed to dt :-)
