### ISSUE TITLE
Non-single-component 'Adobe Deflate' DNG decoding failure

### ISSUE THREAD

**Issue by KristijanZic** [darktable-org/rawspeed#225]
**Describe the bug**
Darktable cannot open the hdr dng image created with Lightroom classic in darkroom.
Also the thumbnails for such images are not shown after importing them.

When opening such image Darktable throws this error:
![Screenshot from 2020-02-20 11-19-29](https://user-images.githubusercontent.com/10299892/74924529-f2cd4d80-53d2-11ea-9012-f6d785c8bbea.png)

**To Reproduce**
1. Download this hdr dng image that I've created in Lightroom classic (created from multiple CR2 images I shot on my Canon 77D):
https://drive.google.com/open?id=1SouINXVW3I2jiWxb-77sQS44x0sjvTkR
2. Import in in Darktable
3. Double click the imported image to open it in darkroom.
You should now see the error.

**Expected behavior**
Dartktable lightable should show thumbnails for such images after importing
Darktable darkroom should load the image and enable the editing of such an image.

**Platform (please complete the following information):**
 - Darktable Version: 3.0.0, 3.0.1 master
OS: Ubuntu 19.10 x86_64 
Host: Inspiron 13-7359 
Kernel: 5.3.0-40-generic 
Uptime: 1 day, 17 hours, 32 mins 
Packages: 1697 (dpkg), 36 (flatpak), 28 (snap)
Shell: bash 5.0.3 
Resolution: 1920x1080 
DE: GNOME 3.34.1 
Theme: Adwaita-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-6500U (4) @ 3.100GHz 
GPU: Intel Skylake GT2 [HD Graphics 520] 
Memory: 6843MiB / 7818MiB

**Comment by jenshannoschwalm** [comment]
btw, with exiv2 -pa there seem to be no exif decoding problems, this is clearly another example of a dual pixel file.
```
Exif.SubImage1.SamplesPerPixel               Short       1  2
Exif.SubImage1.BlackLevel                    Rational    8  524288/256 524288/256 524032/256 524032/256 524544/256 524544/256 524032/256 524032/256
```
@LebedevRI here is one example for the need to analyse more than 4 black level values.

**Comment by LebedevRI** [comment]
Aha.
So that cryptic error most likely was meant to tell us that the `uncompress()`
has run out of space in output (destination) buffer.

**Comment by LebedevRI** [comment]
That will still require darktable-side fix, which i guess is tracked in https://github.com/darktable-org/darktable/issues/4006

**Comment by jenshannoschwalm** [comment]
ooh, one more problem, this file is a sraw with 16bit floats. Simple not supported atm...

**Comment by LebedevRI** [comment]
It seems i got bamboozled, that can't possibly be dual-pixel raw, let me see..

**Comment by LebedevRI** [comment]
Welp, that doesn't look like it decoded correctly :)
![IMG_6374-HDR](https://user-images.githubusercontent.com/88600/75097760-8e231600-55bf-11ea-830e-63cb046e900b.jpg)

**Comment by jenshannoschwalm** [comment]
Whow.
You saw that this is not 32bit but 16bit floats?

**Comment by LebedevRI** [comment]
This is better, i suppose.
![IMG_6374-HDR_01](https://user-images.githubusercontent.com/88600/75099058-54a5d700-55ce-11ea-9e78-9efd802afe64.jpg)

**Comment by LebedevRI** [comment]
@KristijanZic cheers.

**Comment by LebedevRI** [comment]
@jenshannoschwalm 
> You saw that this is not 32bit but 16bit floats?

Note that non-32-bit floatint-point Deflate-compressed images are expanded into 32-bit floating point
https://github.com/darktable-org/rawspeed/blob/cd380bb9a209bd2e7a0e7022b0cab04528d151e7/src/librawspeed/decompressors/DeflateDecompressor.cpp#L236-L244

**Comment by jenshannoschwalm** [comment]
Thanks for pointing to this :-)!
