### ISSUE TITLE
Panasonic DC-GX880 support

### ISSUE THREAD

**Issue by mjaepel** [darktable-org/rawspeed#230]
Hi,

please add support for Panasonic DC-GX880.
I uploaded raw files to raw.pixls.us yesterday. But they are not published yet.

So here are the same samples as zip archive: http://my.eisscholle.net/Panasonic_-_DC-GX880_RAW.zip
I own full rights on the files and published them under CC0.

Thank you,
Marcel

**Comment by LebedevRI** [comment]
Thank you for the samples!
