### ISSUE TITLE
Sony DSC-RX100M7 is not visible in release 3.2.1

### ISSUE THREAD

**Issue by dzavodnikov** [darktable-org/rawspeed#245]
According to the release notes and issue [206](https://github.com/darktable-org/rawspeed/issues/206) _Sony DSC-RX100M7_ should be presented into the release _3.2.1_. But I can not see it into the list of _lenses correction_.

**Comment by parafin** [comment]
lens correction is handled by a separate project: https://lensfun.github.io/lenslist/

support in darktable doesn't cover that part.
