### ISSUE TITLE
Panasonic DC-S5 96MP raws are version 7 - new decompressor needed

### ISSUE THREAD

**Issue by LebedevRI** [darktable-org/rawspeed#246]
```
[rawspeed] (dc-s5_hr_96MP.RW2) virtual rawspeed::RawImage rawspeed::Rw2Decoder::decodeRawInternal(), line 151: Version 7 is unsupported
```

_Originally posted by @LebedevRI in https://github.com/darktable-org/rawspeed/pull/242#issuecomment-717512473_

**Comment by ntsarb** [comment]
A quick note to add that Darktable currently crashes when attempting to open a 96MP raw image file from Panasonic DC-S5.

Also, when I enable the option in the camera to produce a standard resolution file alongside the 96MP one, this (smaller) file will also cause Darktable to crash upon opening.

Is there any way I can support the development of a fix, e.g. by providing sample image files?

**Comment by LebedevRI** [comment]
That was addressed by https://github.com/darktable-org/rawspeed/pull/412.
