### ISSUE TITLE
add support to Samsung GX10 and GX20 DSLR cameras

### ISSUE THREAD

**Issue by jiemdev** [darktable-org/rawspeed#263]
Hello,

Data got from dngmeta.sh and DNG files from https://raw.pixls.us/
Not sure how to fill "Crop" field, so I put Exif.SubImage1.DefaultCropSize information.

	<Camera make="SAMSUNG TECHWIN Co." model="SAMSUNG GX10       ">
		<ID make="Samsung" model="GX10       ">SAMSUNG GX10</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">RED</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">BLUE</Color>
		</CFA>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="0" white="4095"/>
	</Camera>
Exif.SubImage1.DefaultCropSize = 3872 2592

	<Camera make="SAMSUNG TECHWIN Co." model="SAMSUNG GX20       ">
		<ID make="Samsung" model="GX20       ">SAMSUNG GX20</ID>
		<CFA width="2" height="2">
			<Color x="0" y="0">BLUE</Color>
			<Color x="1" y="0">GREEN</Color>
			<Color x="0" y="1">GREEN</Color>
			<Color x="1" y="1">RED</Color>
		</CFA>
		<Crop x="0" y="0" width="0" height="0"/>
		<Sensor black="0" white="4095"/>
	</Camera>
Exif.SubImage1.DefaultCropSize = 4672 3104

Thanks

**Comment by LebedevRI** [comment]
Thank you for the samples!
As you have said, those cameras natively produce DNG files, so no cameras.xml changes are needed.
