### ISSUE TITLE
Support Quad Bayer Remosaic to bayer?

### ISSUE THREAD

**Issue by hanjtcv** [darktable-org/rawspeed#265]
hi, Now dose the project support Quad Bayer Remosaic to bayer pattern? I couldn't find the information. Looking forward to your reply.
Function as follows.
![sony2](https://user-images.githubusercontent.com/42670935/113246118-e9f3be80-92ea-11eb-8b75-625399df64b9.jpeg)

**Comment by LebedevRI** [comment]
There is no handling for Quad Bayer CFA whatsoever.
Which camera produces such raws?
Is there a sample on https://raw.pixls.us/?

**Comment by hanjtcv** [comment]
sony imx 586 and samsung S5KHMX can output quad bayer pattern.

**Comment by LebedevRI** [comment]
I'm sorry, i do not understand the question.

> There is no handling for Quad Bayer CFA whatsoever.

If you have more specific camera support question,
please ensure that there is an appropriate sample on https://raw.pixls.us/ and reopen this.

**Comment by kmilos** [comment]
> sony imx 586 and samsung S5KHMX can output quad bayer pattern.

These are sensors, not cameras.

AFAIK, no camera (e.g. smartphone containing these sensors, or any 3rd party camera app running on a smartphone containing these sensors) provides raw Quad Bayer CFA output...

If you know otherwise, please provide samples.
