### ISSUE TITLE
Fujifilm X-E4 support

### ISSUE THREAD

**Issue by zinga666** [darktable-org/rawspeed#268]
Hi,

could you please add support for the Fujifilm X-E4?

It has the same sensor (and CPU) as the X-S10 and X-T4 and someone has already uploaded image samples to raw.pixls.us.

If it is just a matter of using the same data as for the X-S10 in #254 then I could do the copy/paste work as well (if it helps).

**Comment by LebedevRI** [comment]
This was fixed by e8b2af41a065d74d9b7ff29f85675191ed886d71.
