### ISSUE TITLE
reading programmatically created DNG fails

### ISSUE THREAD

**Issue by sniklaus** [darktable-org/rawspeed#270]
I am working with a raw Bayer bitstream from an image sensor and would like to further process this data using tools like darktable, which is why I need to convert it to a DNG. To convert this bitstream to a DNG I just use Adobe's DNG SDK [1] similar to what is done at this reference [2]. This is an example DNG that I created in this way: [data-2349511-8xq8l9m0mm0pt5mwjeha.dng.zip](https://github.com/darktable-org/rawspeed/files/6455438/data-2349511-8xq8l9m0mm0pt5mwjeha.dng.zip)

The referenced example can be loaded by Lightroom, RawTherapee, and LibRaw just fine but darktable/rawspeed is unable to read it. I already brought this issue up in the darktable repo but was referred to this repo instead: https://github.com/darktable-org/darktable/issues/8718

Is this a bug in rawspeed, or is my DNG missing some important meta information? One thing I tried is adding a thumbnail/preview to the DNG when exporting it but that didn't seem to make a difference. Thanks!

[1] https://www.adobe.com/support/downloads/dng/dng_sdk.html
[2] https://github.com/mgharbi/mit_png2dng/blob/master/dng_sdk/projects/dng_converter/dng_converter/dng_converter.cpp

**Comment by parafin** [comment]
I have no experience with DNG SDK, but your DNG file doesn't look like raw bayer DNG - it has Samples Per Pixel set to 3, which in indicative of demosaiced data. Maybe you mixed something up when you were trying to add a thumbnail/preview? Preview is not needed for darktable to be able to open a DNG. What might be missing is a AsShotNeutral tag for white balance.

**Comment by sniklaus** [comment]
You hit the nail on the head, I just needed to set the samples per pixel to 1 and everything works as expected now (aside from the white balance). Thanks for looking into this! Closing this issue since I would consider this a bug in the DNG itself rather than rawspeed.
