### ISSUE TITLE
Improve the ci feedback

### ISSUE THREAD

**Issue by axxel** [darktable-org/rawspeed#29]
I'd like to suggest to remove the codecov tests from the set of tests that take part in the final "sucess or failure" conclusion of the ci system. E.g. the failing of #27 makes no sense to me. I see the value those tests have on a code base with full or nearly full test coverage but right now they just hide the really useful information the other two tests provide.

**Comment by LebedevRI** [comment]
True, commit statuses from codecov.io are not as useful right now as they would be with raw-sample-based tests. For now i will disable *commit statuses*, but not pr comments.

**Comment by axxel** [comment]
Thanks!
