### ISSUE TITLE
#294 breaks compile on Ubuntu 18.04

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/rawspeed#303]
Ubuntu 18.04 still uses cmake 3.10.2.  18.04 still has 19 months unttil EOL. #294 changed the minimum to 3.13.

Editing the CMakeLists.txt file and changing the version back results in successful compilation.

**Comment by LebedevRI** [comment]
Hi.

As per https://wiki.ubuntu.com/Releases, Ubuntu 18.04 is indeed LTS,
with "End of Standard Support" advertised as April 2023 (18 months from now).

However, the fact whether or not particular ubuntu distro is EOS/EOL
only matters to the ubuntu itself and the packages provided for that particular distro.
It does not mean that every future version of every project that is packaged in that release
must be buildable on that version of that particular distro.

Generally, i try to be very reasonable with required versions,
and try to, if there isn't a good reason not to, not require ones newer than
a. 3 years old
b. available in debian stable and latest ubuntu lts

In this case, all of the above is satisfied.

https://apt.kitware.com/ might be helpful.

**Comment by wpferguson** [comment]
I understand.  Thanks for the pointer to https://apt.kitware.com/.  That worked.

**Comment by LebedevRI** [comment]
I'm sorry for the problems, i understand that such things are never fun.
