### ISSUE TITLE
Add support for Sony A7 IV

### ISSUE THREAD

**Issue by cryptomilk** [darktable-org/rawspeed#328]
Hi Roman,

I've just uploaded RAW files for the A7M4 to raw.pixls.us. Let me know if you need any additional pictures.

Thanks!

**Comment by kmilos** [comment]
See also https://github.com/darktable-org/darktable/issues/10556

**Comment by LebedevRI** [comment]
Feel free to submit patches.

**Comment by kmilos** [comment]
Not supported by ADC yet...

**Comment by kmilos** [comment]
Unsurprisingly, [the same "WTH Sony" gotchas are present as in the ILCE-1 case for the new lossless mode](https://github.com/darktable-org/darktable/issues/8523):

1. Both tile and strip-based storage tags are present in the full resolution IFD, when they should be mutually exclusive (tile only)
2. Image size is unnecessarily increased to integer multiple of tile size

**Comment by kmilos** [comment]
> Not supported by ADC yet...

ADC 14.1 w/ support released yesterday.

**Comment by kmilos** [comment]
FYI, the dngmeta.sh tool output for cameras.xml is this:

```xml
        <Camera make="SONY" model="ILCE-7M4">
                <ID make="Sony" model="ILCE-7M4">Sony ILCE-7M4</ID>
                <CFA width="2" height="2">
                        <Color x="0" y="0">RED</Color>
                        <Color x="1" y="0">GREEN</Color>
                        <Color x="0" y="1">GREEN</Color>
                        <Color x="1" y="1">BLUE</Color>
                </CFA>
                <Crop x="0" y="0" width="0" height="0"/>
                <Sensor black="512" white="16383"/>
        </Camera>
```

but I won't be submitting a patch as I don't know the exact methodology preferred here to determine the crop.

**Comment by cryptomilk** [comment]
@kmilos Can you also paste the adobe coeff (color matrix)?

**Comment by kmilos** [comment]
Sure, it was already merged above, but here goes:

`{ "Sony ILCE-7M4", { 7460,-2365,-588,-5687,13442,2474,-624,1156,6584 } },`

P.S. Don't use auto-close keywords in rawspeed, as it messes up Roman's [triage system](https://github.com/orgs/darktable-org/projects/1).

**Comment by cryptomilk** [comment]
Ah, they are already in darktable master. Nice :-)
