### ISSUE TITLE
I need help of raw data

### ISSUE THREAD

**Issue by HanalogInstruments** [darktable-org/rawspeed#368]
Hi,

I have some jpeg corrupted all  header only raw data, can i use this library to decode raw data from jpeg?

**Comment by LebedevRI** [comment]
> I have some jpeg corrupted all header only raw data,

I'm having trouble parsing this part of the message.

> can i use this library to decode raw data from jpeg?

Unless the source raw image was embedded into the exported JPEG (into EXIF metadata somewhere),
that is simply impossible. RAW->JPEG export/render is a one-way process.
