### ISSUE TITLE
P7700 support

### ISSUE THREAD

**Issue by phweyland** [darktable-org/rawspeed#373]
Hi, some people and I have uploaded raw files for this camera on raw.pixls.us as requested.
This camera appears now on this site [here](https://raw.pixls.us/getfile.php/5328/nice/Nikon%20-%20Coolpix%20P7700%20-%2012bit%20compressed%20((7))%20(4:3).NRW).
There is only one raw format for this camera.
But the file cameras.xml still show "no samples":
```
<Camera make="NIKON" model="COOLPIX P7700" mode="12bit-compressed" decoder_version="5" supported="no-samples">
```
Could you please fix this ?
Thanks in advance

**Comment by LebedevRI** [comment]
https://github.com/darktable-org/rawspeed/commit/4a64fcc47213182f27ac390b9ca15e05b8988db0
