### ISSUE TITLE
Fujifilm X-H2S Support

### ISSUE THREAD

**Issue by etrigan63** [darktable-org/rawspeed#374]
Please add support for uncompressed, lossless compressed and compressed raw files. I can submit raw files if needed. Just point me to where you want them.

**Comment by cytrinox** [comment]
Please upload the samples here: https://raw.pixls.us/

**Comment by etrigan63** [comment]
Done!

**Comment by kmilos** [comment]
Please try out adding the following to your cameras.xml and report what you find (most likely we'll have to update the crop and the CFA pattern arrangement):

```
	<Camera make="FUJIFILM" model="X-H2S">
		<ID make="Fujifilm" model="X-H2S">Fujifilm X-H2S</ID>
		<CFA2 width="6" height="6">
			<ColorRow y="0">GGRGGB</ColorRow>
			<ColorRow y="1">GGBGGR</ColorRow>
			<ColorRow y="2">BRGRBG</ColorRow>
			<ColorRow y="3">GGBGGR</ColorRow>
			<ColorRow y="4">GGRGGB</ColorRow>
			<ColorRow y="5">RBGBRG</ColorRow>
		</CFA2>
		<Crop x="0" y="6" width="-78" height="-12"/>
		<Sensor black="1024" white="16383"/>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">12836 -5909 -1032</ColorMatrixRow>
				<ColorMatrixRow plane="1">-3087 11132 2236</ColorMatrixRow>
				<ColorMatrixRow plane="2">-35 872 5330</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera> 
	<Camera make="FUJIFILM" model="X-H2S" mode="compressed">
		<ID make="Fujifilm" model="X-H2S">Fujifilm X-H2S</ID>
		<CFA2 width="6" height="6">
			<ColorRow y="0">GGRGGB</ColorRow>
			<ColorRow y="1">GGBGGR</ColorRow>
			<ColorRow y="2">BRGRBG</ColorRow>
			<ColorRow y="3">GGBGGR</ColorRow>
			<ColorRow y="4">GGRGGB</ColorRow>
			<ColorRow y="5">RBGBRG</ColorRow>
		</CFA2>
		<Crop x="0" y="6" width="-78" height="-12"/>
		<Sensor black="1024" white="16383"/>
		<ColorMatrices>
			<ColorMatrix planes="3">
				<ColorMatrixRow plane="0">12836 -5909 -1032</ColorMatrixRow>
				<ColorMatrixRow plane="1">-3087 11132 2236</ColorMatrixRow>
				<ColorMatrixRow plane="2">-35 872 5330</ColorMatrixRow>
			</ColorMatrix>
		</ColorMatrices>
	</Camera> 
```

Probably the "new" lossy compressed mode is not yet supported, like it is still the case w/ T4, E4, S10, etc...

**Comment by etrigan63** [comment]
No error message, but the image is either blank white or magenta.
[image: image.png]
[image: photo]
Carlos Echenique
Photographer at  CE Photographic
P  305.219.2433  <305.219.2433>
E  ***@***.***  ***@***.***>
W  cephotographic.com  <http://cephotographic.com>
<http://instagram.com/cephotographic> <http://facebook.com/cephotos>
<http://www.flickr.com/photos/echenique>

"A day without sunshine is like, you know, night." - Steve Martin.
Create your own email signature
<https://www.wisestamp.com/create-own-email-signature/?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own&srcid=>

**Comment by kmilos** [comment]
I had already updated the settings above in the meantime, please give it a go again.

**Comment by cytrinox** [comment]
Only two samples uploaded, but H2S supports 3 modes (uncompresses, lossless, compressed). Please uploaded the missing sample, too.

**Comment by etrigan63** [comment]
> I had already updated the settings above in the meantime, please give it a go again.

This one is much better. Colors are correct. Filmic RGB underexposes an additional stop. Small crop is needed due to sensor size difference. This is more pronounced if manual lens correction is applied. `lensfun` will need an update for the sensor.

**Comment by etrigan63** [comment]
> Only two samples uploaded, but H2S supports 3 modes (uncompresses, lossless, compressed). Please uploaded the missing sample, too.

Lossy compressed sample uploaded.

I also uploaded three daylight shots.

**Comment by mwperina** [comment]
Hi,
I've tried to append above code into cameras.xml, but when I'm trying to open uncompressed RAF file in Darkroom, following error is shown:

```
`Fujifilm X-H2S' color matrix not found!
```

I'm using Darktable 3.8.1 on Fedora 35. 

Is there anything I can help with to include X-H2S support into Darktable?

Thanks,
Martin

**Comment by kmilos** [comment]
This approach works only from dt 4.0

**Comment by etrigan63** [comment]
The XML provided no longer works as of dt 4.0.1. The X-H2S firmware updated to 2.0 but i don't think they changed the file format.

**Comment by mwperina** [comment]
After upgrade to Darktable 4.0.1 I can import uncompressed RAF from X-H2S without any problem and after working on more than 50 photos I haven't found any obvious issue, images are processed fine. So is there anything blocking us from getting X-H2S support merged?
