### ISSUE TITLE
Some different black points at different ISO, Canon EOS D60

### ISSUE THREAD

**Issue by PeterWem** [darktable-org/rawspeed#376]
```
<Camera make="Canon" model="Canon EOS D60">
		<ID make="" model="">Canon EOS D60</ID>
		<Sensor black="132" white="4000"/>
		<Sensor black="137" white="4000" iso_list="800"/>
	</Camera>
```
![Skärmbild från 2022-07-25 23-32-40](https://user-images.githubusercontent.com/34200649/180877668-7d41e5e8-ed54-4ff3-87a4-ff563d3f0d3b.png)
```

exiv2 -pt CRW_7102.dng 2>/dev/null | grep ColorMatrix2
Exif.Image.ColorMatrix2                      SRational   9  6211/10000 -1358/10000 -896/10000 -8557/10000 15766/10000 3012/10000 -3001/10000 3507/10000 8567/10000
```

![Skärmbild från 2022-07-25 23-34-52](https://user-images.githubusercontent.com/34200649/180877937-96f3023a-9d55-4653-a185-0c1a3907b410.png)

**Comment by PeterWem** [comment]
The optical black area in rawspeed is wrong why the picture will look green at high ISO. I will correct it with a PR instead.

**Comment by LebedevRI** [comment]
If they are, please feel free to PR them.

But the whole of "black 'area'" handling is completely broken (#389, etc).
