### ISSUE TITLE
Different white/black point, Canon EOS 30D

### ISSUE THREAD

**Issue by PeterWem** [darktable-org/rawspeed#377]
```
<Camera make="Canon" model="Canon EOS 30D">
		<ID make="" model="">Canon EOS 30D</ID>
		<Sensor black="0" white="3300"/>
	</Camera>
```
![Skärmbild från 2022-07-25 23-40-13](https://user-images.githubusercontent.com/34200649/180878615-5ce97ce0-38d7-4112-91b3-d44f6764c4e2.png)

```


$ exiv2 -pt IMG_6902.dng 2>/dev/null | grep ColorMatrix2
Exif.Image.ColorMatrix2                      SRational   9  6256/10000 -303/10000 -1000/10000 -7879/10000 15621/10000 2396/10000 -1713/10000 1905/10000 7047/10000
```
![Skärmbild från 2022-07-25 23-40-35](https://user-images.githubusercontent.com/34200649/180878665-f45e9ba0-4908-4dbe-9627-0e8392ee2439.png)

**Comment by LebedevRI** [comment]
We now read them from makernotes.
