### ISSUE TITLE
CR2 decoder (and others) should read levels from the raw

### ISSUE THREAD

**Issue by aquatix** [darktable-org/rawspeed#391]
When editing my photo's in DT, I came across the issue where the whitepoint being used wasn't the one that's in the CR2, and which exiftool shows.

All cr2 should read levels from the raws, here's an example:

https://discuss.pixls.us/t/struggling-with-direct-light/33199

According to exiftool the raw whitepoint should be 11765 but DT sets it to 13653

I'm running Ubuntu 22.10 with Darktable 4.0.1, but another user had the same issue with DT 4.1 from master

**Comment by AxelG-DE** [comment]
Here is "the other user" :-P

Experienced that through above pic as with the initial values, the raw-overexposed indicator does not show obviously blown highlights.

**Comment by kmilos** [comment]
Closing in favor of https://github.com/darktable-org/rawspeed/issues/417
