### ISSUE TITLE
The change to needing cmake 3.18 prevents building darktable under Ubuntu 20.04

### ISSUE THREAD

**Issue by RawConvert** [darktable-org/rawspeed#400]
Ubuntu is of course one of the most widely used distros, if not The most used, and 20.04 is long-term supported, which makes it attractive to many users.  Rawspeed has recently changed and now needs cmake version 3.18, whereas 20.04 only has cmake 3.16.3.
Is it really necessary to move to 3.18 and please please, if it's possible, can it go back to where it was (or 3.16.3 say)?

I just searched this repository for "cmake 3.18" hoping to understand why it's been advanced but only one item was found and there seems to be no info about why upgraded.

![cmake](https://user-images.githubusercontent.com/16868433/202673310-12b72b69-caa6-4cd0-8c8a-791359028962.jpg)

Thanks

**Comment by kmilos** [comment]
@LebedevRI FYI, this didn't show up straight away w/ the darktable CI because (fortunately or not) the [Ubuntu 20.04 GHA runner has a more recent CMake installed in addition.](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md)

**Comment by LebedevRI** [comment]
Hello.

As we have discussed numerous times, the fact of whether or not
some distribution is supported only affects the support
for the distribution by the distribution's maintainers:
https://wiki.ubuntu.com/supportperiod

It does not and can not incur an immediate requirement
for whatever downstream to support any particular distribution
that is still supported by the distribution's maintainers.

Ubuntu, much like debian, has -updates, and -backport repos,
and one can ask ubuntu cmake maintainers to consider a backport.
Alternatively, there's https://apt.kitware.com/

Lagging behind and supporting cmake-3.16/gcc10/clang10
for the forceeable future (3+ years is essentially an ethernity) is unreasonable.
I would recommend to bring this up with ubuntu cmake maintainer.

**Comment by LebedevRI** [comment]
> @LebedevRI FYI, this didn't show up straight away w/ the darktable CI because (fortunately or not) the [Ubuntu 20.04 GHA runner has a more recent CMake installed in addition.](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md)

Yeah, not surprised.
This is why i always try not to use the provided github image,
but do `container: image: <name of barebones debian ubuntu docker image>`,
so there's no confusion over what is and isn't there.
