### ISSUE TITLE
add support for X-T5

### ISSUE THREAD

**Issue by andyczerwonka** [darktable-org/rawspeed#407]
Please add support for the Fujifilm X-T5 lossless compressed.

**Comment by kmilos** [comment]
Please search before opening new issues.

Duplicate of https://github.com/darktable-org/darktable/issues/12952 and https://github.com/darktable-org/rawspeed/pull/406

**Comment by LebedevRI** [comment]
Duplicate of https://github.com/darktable-org/darktable/issues/12952

**Comment by andyczerwonka** [comment]
> Please search before opening new issues.
> 
> Duplicate of [darktable-org/darktable#12952](https://github.com/darktable-org/darktable/issues/12952) and #406

I did, but not the separate repository.
