### ISSUE TITLE
Sony A7RM5 (ILCE-7RM5) camera support

### ISSUE THREAD

**Issue by ghost** [darktable-org/rawspeed#409]
Hello

Would it be possible to include raw support for the Sony A7RM5 (ILCE-7RM5) please?

Thank you very much!

**Comment by kmilos** [comment]
Duplicate of https://github.com/darktable-org/darktable/issues/13035 and https://github.com/darktable-org/darktable/issues/12985

**Comment by da-phil** [comment]
Rawspeed already supports uncompressed & lossy compressed images, support for lossless compression (L) is prepared in the following PR: https://github.com/darktable-org/rawspeed/pull/483
Lossless compression M/S is going to be future work I guess.

**Comment by LebedevRI** [comment]
c38746dae23d6f8fca594be50678bc55607da268
