### ISSUE TITLE
Color-space after ColorMatrix transformation

### ISSUE THREAD

**Issue by gustavolsson** [darktable-org/rawspeed#429]
Hello and thanks for creating and maintaining rawspeed! I'm using the library to create a simple raw editor but I find it difficult to figure out some things:

1. Is the raw pixel data we get unprocessed sensor data (uniformly scaled to appropriate ranges)? This is evident if there is a CFA because the monochrome values need to be manually converted to the nondescript "RED" "GREEN" and "BLUE" channels, but is it also the case for non-CFA images?

2. I assume that the ColorMatrix from the camera metadata is never applied by rawspeed?

3. What color-space is the RGB values in after a transformation by the ColorMatrix metadata value?

4. Are the white balance metadata coefficients supposed to be used as-is or are they in a particular color-space? I.e. do I need to convert the RGB values into e.g. [LMS color space](https://en.wikipedia.org/wiki/LMS_color_space) before applying the scaling as [outlined here](http://www.brucelindbloom.com/index.html?Eqn_ChromAdapt.html)?

I think it would help to document this in the `data/README.md` file. I'm open to doing this with some guidance!

**Comment by LebedevRI** [comment]
> 1. Is the raw pixel data we get unprocessed sensor data (uniformly scaled to appropriate ranges)?

It depends on your definition of "unprocessed" and "scaled", but basically yes,
library does not touch the data in ways that are not strictly required for decoding itself.
It doesn't even normalize the data.

> This is evident if there is a CFA because the monochrome values need to be manually converted to the nondescript "RED" "GREEN" and "BLUE" channels, but is it also the case for non-CFA images?

Notionally - yes.

> 2. I assume that the ColorMatrix from the camera metadata is never applied by rawspeed?

Correct.

> 3. What color-space is the RGB values in after a transformation by the ColorMatrix metadata value?

That color matrix is effectively taken from DNG's `ColorMatrix2`, and is notionally for illuminant `7` (D65),

> Description
> ColorMatrix2 defines a transformation matrix that converts XYZ values to reference camera
> native color space values, under the second calibration illuminant. The matrix values are
> stored in row scan order.

> 4. Are the white balance metadata coefficients supposed to be used as-is or are they in a particular color-space? I.e. do I need to convert the RGB values into e.g. [LMS color space](https://en.wikipedia.org/wiki/LMS_color_space) before applying the scaling as [outlined here](http://www.brucelindbloom.com/index.html?Eqn_ChromAdapt.html)?

I'm not familiar with chromatic adaptation stuff. Normally, you'd just use them as-is.

**Comment by LebedevRI** [comment]
I'm going to close this.
If you have thoughts on how the docs could be improved, please feel free to PR that.

**Comment by gustavolsson** [comment]
Thank you for your quick and informative reply!

> That color matrix is effectively taken from DNG's ColorMatrix2, and is notionally for illuminant 7 (D65),

I will read up on DNG and its metadata, thanks for the pointer. Do you know if this data comes from Adobe's in-house camera calibration (encoded into the Adobe DNG converter tool) or if the source data is in the original raw file itself? If it's from Adobe's calibration process, I find it fascinating that the "unedited" color science of many raw editors comes not from the camera itself but from Adobe. (I've seen other open source libraries and editors use this DNG metadata)

> I'm going to close this.
> If you have thoughts on how the docs could be improved, please feel free to PR that.

Sounds good. Thanks again for the help!

**Comment by kmilos** [comment]
> or if the source data is in the original raw file itself

Most raw formats don't provide this information (or, it is not known if the vendor [MakerNotes](https://exiftool.org/TagNames/index.html) contain that information).

**Comment by LebedevRI** [comment]
> Do you know if this data comes from Adobe's in-house camera calibration (encoded into the Adobe DNG converter tool) or if the source data is in the original raw file itself?

I believe, //some// non-DNG raw formats do contain color matrix in the metadata,
but i don't think we read it. But i'm not sure if that is used in ADC, or what the source for ADC matrices is.
