### ISSUE TITLE
Required compiler too strict

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/rawspeed#550]
Currently we require GCC 12.x or CLang 14.x to build rawspeed.

The Debian 11 release which has been released the Jun 10th 2023 has only GCC 10.x and CLang 13.x.

This means that we cannot compile darktable on a version which is about 5 months old.

This is really too strict. Can we keep compatibility with CLang 13.x to at least have a way to compile on Debian 11 and possibly other distribution on the same situation?

**Comment by LebedevRI** [comment]
> The Debian 11 release which has been released the Jun 10th 2023 has only GCC 10.x and CLang 13.x.

This is not true.
1. Debian 11 "bullseye" was released August 14th, 2021, i.e. 2 years ago.
2. Debian 12 "bookworm" was released June 10th, 2023, i.e. 5 months ago.

As per the [supported compiler policy](https://github.com/darktable-org/darktable/blob/ff5095cc990126aede3ad605dc1f9ebe455e2b0d/cmake/compiler-versions.cmake#L1-L37), that we have discussed a number of times elsewhere, this is working as intended, quote:
```
# We strive to keep the [darktable] software releases (but not necessarily
# development versions!) buildable with the versions of the dependencies
# provided out-of-the-box in the following distributions:
# * debian stable
# * latest(!) ubuntu LTS
# * oldest(*) maintained macOS release (assuming current cadence of
#   one major macOS release per year, and 3 (three) year shelf-life,
#   so last three releases are to be supported)
```
Debian 12 "bookworm"  is stable, and it is supported. Debian 11 "bullseye" is now oldstable, and is not supported.
