### ISSUE TITLE
Alias of Konica Minolta Maxxum 7D in cameras.xml seems incorrect?

### ISSUE THREAD

**Issue by ByronJY** [darktable-org/rawspeed#757]
I own a Japan version Maxxum 7D, α-7 Digital.
Darktable could not load the `.MRW` files of this camera.
I tried add `<Alias id="ALPHA-7 DIGITAL">ALPHA-7 DIGITAL</Alias>`, and it works.

**Comment by kmilos** [comment]
Please share a sample.

**Comment by ByronJY** [comment]
[PICT0011.zip](https://github.com/user-attachments/files/17533411/PICT0011.zip)

**Comment by kmilos** [comment]
Thank you!

Confirming
```
$ exiv2 -pa PICT0011.MRW | grep Image.M[ao]
Exif.Image.Make                              Ascii      16  KONICA MINOLTA
Exif.Image.Model                             Ascii      16  ALPHA-7 DIGITAL
```

**Comment by ByronJY** [comment]
Thank you!

**Comment by kmilos** [comment]
https://raw.pixls.us/ is back up, please upload the samples directly. @ByronJY

**Comment by LebedevRI** [comment]
> https://raw.pixls.us/ is back up, please upload the samples directly. [@ByronJY](https://github.com/ByronJY)

RPU is still not up. (upload not working)

**Comment by ByronJY** [comment]
Ah, that makes sense.
I tried several times, it always shows "Upload disabled. Busy rebuilding."
By the way, what is RPU?

**Comment by LebedevRI** [comment]
`[R]aw.[P]ixls.[U]s`

**Comment by ByronJY** [comment]
Oh! I see.

**Comment by kmilos** [comment]
@ByronJY The RPU upload is working again, please contribute the sample directly.

**Comment by ByronJY** [comment]
Uploaded.

**Comment by LebedevRI** [comment]
Verified upload, thank you for contributing the sample!
