### ISSUE TITLE
Bad pixel correction for DNGs is broken

### ISSUE THREAD

**Issue by axxel** [darktable-org/rawspeed#79]
See https://redmine.darktable.org/issues/10078.

Example image: https://raw.pixls.us/getfile.php/683/raw/RAW_CANON_POWERSHOT_SX130IS_CHDK.DNG

I stumbled on this issues while cleaning up the DngOpcode classes. This has almost certainly never worked (I found 2 separate issues).

I have a complete rewrite of the DngOpcode classes, fixing this issue (among others). Just waiting for #75 to be merged.

**Comment by LebedevRI** [comment]
Coverity CID 1025896 and 1025897 are probably related.

**Comment by axxel** [comment]
> Coverity CID 1025896 and 1025897 are probably related.

Yes and no:
 * affecting some kind of bad pixel correction (float images): yes
 * completely preventing bad pixel correction of DNGs: no
